
CaseStudyI : main.cpp
	g++ -g -O2 -Wall -c src/SpinodalDecomposition.cpp
	g++ -g -O2 -Wall -o CaseStudyI main.cpp SpinodalDecomposition.o
	
run : CaseStudyI
	./CaseStudyI 
	
clean : CaseStudyI Output/* Results/* SpinodalDecomposition.o
	rm CaseStudyI Output/* Results/* SpinodalDecomposition.o
	

	