CaseStudyI : main.cpp
	g++ -g -O2 -Wall -o CaseStudyI main.cpp 
	
run : CaseStudyI
	./CaseStudyI 
	
clean : CaseStudyI Output/Initial_Profile.*  Output/Chemical_Potential_at_t_* Output/Derivative_at_t_* Output/Concentration_Profile_t_* Output/Gibbs_Energy.dat
	rm CaseStudyI Output/Initial_Profile.* Output/Chemical_Potential_at_t_* Output/Derivative_at_t_* Output/Concentration_Profile_t_* Output/Gibbs_Energy.dat